export const ADD_INPUT_PROVINCE = 'ADD_INPUT_PROVINCE';
export const EDIT_INPUT_PROVINCE = 'EDIT_INPUT_PROVINCE';
export const REMOVE_INPUT_PROVINCE = 'REMOVE_INPUT_PROVINCE';
export const LOAD_WEATHERS = 'LOAD_WEATHERS';
export const LOAD_WEATHERS_SUCCESS = 'LOAD_WEATHERS_SUCCESS';
export const LOAD_WEATHERS_ERROR = 'LOAD_WEATHERS_ERROR';
