export const LOAD_WEATHER = 'LOAD_WEATHER';
export const LOAD_WEATHER_SUCCESS = 'LOAD_WEATHER_SUCCESS';
export const LOAD_WEATHER_ERROR = 'LOAD_WEATHER_ERROR';
export const LOAD_PROVINCE_ID = 'LOAD_PROVINCE_ID';
export const CONVERT_WEATHER_DETAIL = 'CONVERT_WEATHER_DETAIL';
